### PR TITLE
"Try It Live!" button

### LINKED ISSUE #50: Add a "Try it live!" button that the user needs to press prior to showing the embedded iframe
cc. @davidbrochart

### Problem

When jupyterlite-sphinx embeds JupyterLite in a documentation page, it can be tens of MB for the viewer to download, this can be really annoying if the viewer is not interested in testing JupyterLite but just want to see the rest of the docs.

### Proposed Solution

We should add the possibility to show a button "Try it live!" that the viewer needs to press before the iframe is added to the page.

Wishlist for this feature:
- make this an opt-in or an opt-out
- make the "Try it live!" prompt customizable

### PR DESCRIPTION
**Pull request by martinRenou**
Fix #50

tryitbutton

### CODE REVIEW

**Comment by jtpio** [comment]
Looking good!

Wondering whether adding the "thread" of the bulb would make it even more explicit this is an embedded JupyterLite app? 

image

**Comment by martinRenou** [comment]
Yes, I was also thinking of mimicking slightly the JupyterLab spinner with 3 yellow moons rotating around the bulb. What do you think?

I implemented this using pure CSS, so no SVG involved. Maybe using SVG could simplify the setup?

**Comment by martinRenou** [comment]
@jtpio if you don't mind, we could go ahead with the current state of this PR and discuss look improvements ideas in an issue?

**Comment by jtpio** [comment]
Sure thing.

**Pull request merged**
