### PR TITLE
add a github link to the documentation

### LINKED ISSUE #80: No link to GitHub from the docs
### Problem

The docs don't seem to include any links back to this GitHub repository.

### PR DESCRIPTION
**Pull request by 12rambau**
Fix #80

everything is in the title ;-)

### CODE REVIEW

**Review by martinRenou — APPROVED** [review]
Thank you!

**Comment by martinRenou** [comment]
@12rambau I don't see the Github link appearing in the rtd build: https://jupyterlite-sphinx--82.org.readthedocs.build/en/82 Where should it appear?

**Comment by 12rambau** [comment]
oups I'm not seeing it as well that's weird it should be after the light/dark button. Let me check the parameter again and do a local build before my next commit

**Comment by 12rambau** [comment]
@martinRenou I was one typo away from setting it correctly. It worked on my local build but I can't see the RDT test anymore (maybe because you already approved the change).

**Comment by martinRenou** [comment]
Thanks! Triggering a build

**Comment by martinRenou** [comment]
Thanks!

**Pull request merged**
